ToDoList/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class Category
    {
        public int Id { get; set; }
        [Required]
        public string CategoryName { get; set; }

        public string CategoryColour { get; set; }
        public ICollection<ToDo>? ToDos { get; set; }
    }
}

ToDoList/Models/Project.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class Project
    {
        public int Id { get; set; }

        [Required]
        public string ProjectName { get; set; }

        public string ProjectColour { get; set; }
    }
}

ToDoList/Pages/Category.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDoList.Data;
using ToDoList.Models;

namespace ToDoList.Pages
{
    public class CategoryModel : PageModel
    {
        private readonly ToDoList.Data.ToDoListContext _context;
        private SQLToDoRepository sQLToDoRepository;

        public IList<ToDo> CategoryTaskList { get; set; } = default!;
        public IList<Project> ProjectsList { get; set; } = default!;
        public IList<Category> CategoriesList { get; set; } = default!;

        public bool wantProjects = false;
        public bool wantCategories = true;
        public bool showDetails = false;
        public bool showCategoryInfo = false;
        public int DetailsId = 0;
        public int categoryId = 0;

        public CategoryModel(ToDoList.Data.ToDoListContext context)
        {
            _context = context;
            sQLToDoRepository = new SQLToDoRepository(_context);
        }
        public void OnGet(int cId, int? nav, int? id, bool? info)
        {
            if (_context.ToDo != null)
            {
                CategoryTaskList = (IList<ToDo>)sQLToDoRepository.GetOneCategory(cId);
            }
            if (_context.Project != null)
            {
                ProjectsList = (IList<Project>)sQLToDoRepository.GetAllProjects();
            }

            if (_context.Category != null)
            {
                CategoriesList = (IList<Category>)sQLToDoRepository.GetAllCategories();
            }

            categoryId = cId;

            if ((info != null) && (bool)info)
            {
                showCategoryInfo = true;
            }
            else if ((id != null) && (CategoryTaskList.Select(p => p.Id).ToList().Contains((int)id)))
            {
                showDetails = true;
                DetailsId = (int)id;
            }

            if (nav != null)
            {
                if ((int)nav == 1)
                {
                    wantProjects = true;
                    wantCategories = false;
                }
                else
                {
                    wantProjects = false;
                    wantCategories = true;
                }
            }
        }

        public IActionResult OnPostUpdate()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.UpdateTask(Int32.Parse(Request.Form["id"]), Request.Form["upd"]);
            }
            return RedirectToPage("/Category", new { cid = Request.Form["cid"] });
        }

        public IActionResult OnPostUpdateDetails()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.UpdateTask(Int32.Parse(Request.Form["id"]), Request.Form["upd"]);
            }
            return RedirectToPage("/Category", new { id = Request.Form["id"], cid = Request.Form["cid"] });
        }

        public IActionResult OnPostAdd()
        {
            if (Request.Form["taskname"] != "")
            {
                var newToDo = new ToDo
                {
                    TaskName = Request.Form["taskname"],
                    Categories = new List<Category> { sQLToDoRepository.GetCategoryInfo(Int32.Parse(Request.Form["cid"])) },
                    IsUrgent = false
                };
                sQLToDoRepository.AddNewTask(newToDo);
            }
            return RedirectToPage("/Category", new { cid = Request.Form["cid"] });
        }

        public IActionResult OnPostAddProject()
        {
            if (Request.Form["pname"] != "")
            {
                var newProject = new Project
                {
                    ProjectName = Request.Form["pname"],
                    ProjectColour = "#e2e2e2;"

                };
                sQLToDoRepository.AddNewProject(newProject);
            }
            return RedirectToPage("/Category", new { cid = Request.Form["cid"], nav = 1 });
        }

        public IActionResult OnPostAddCategory()
        {
            if (Request.Form["cname"] != "")
            {
                var newCategory = new Category
                {
                    CategoryName = Request.Form["cname"],
                    CategoryColour = "#e2e2e2;"
                };
                sQLToDoRepository.AddNewCategory(newCategory);
            }
            return RedirectToPage("/Category", new { cid = Request.Form["cid"], nav = 2 });
        }

        public IActionResult OnPostChangeTaskName()
        {
            if (Request.Form["newtname"] != "")
            {
                sQLToDoRepository.UpdateTaskName(Int32.Parse(Request.Form["id"]), Request.Form["newtname"]);
            }
            return RedirectToPage("/Category", new { id = Request.Form["id"], cid = Request.Form["cid"] });
        }

        public IActionResult OnPostDeleteTask()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.DeleteTask(Int32.Parse(Request.Form["id"]));
            }
            return RedirectToPage("/Category", new { cid = Request.Form["cid"] });
        }

        public IActionResult OnPostDeleteCategory()
        {
            if (Request.Form["cid"] != "")
            {
                sQLToDoRepository.DeleteCategory(Int32.Parse(Request.Form["cid"]));
            }
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostChangeCategoryName()
        {
            if (Request.Form["newcname"] != "")
            {
                sQLToDoRepository.UpdateCategoryName(Int32.Parse(Request.Form["cid"]), Request.Form["newcname"]);
            }
            return RedirectToPage("/Category", new { cid = Request.Form["cid"], info = true });
        }
    }
}

ToDoList/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ToDoList.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ToDoList/Pages/Inbox.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDoList.Data;
using ToDoList.Models;

namespace ToDoList.Pages
{
    public class InboxModel : PageModel
    {
        private readonly ToDoList.Data.ToDoListContext _context;
        private SQLToDoRepository sQLToDoRepository;

        public IList<ToDo> InboxList { get; set; } = default!;
        public IList<Project> ProjectsList { get; set; } = default!;
        public IList<Category> CategoriesList { get; set; } = default!;

        public bool wantProjects = false;
        public bool wantCategories = false;
        public bool showDetails = false;
        public int DetailsId = 0;

        public InboxModel(ToDoList.Data.ToDoListContext context)
        {
            _context = context;
            sQLToDoRepository = new SQLToDoRepository(_context);
        }
        public void OnGet(int? nav, int? id)
        {
            if (_context.ToDo != null)
            {
                InboxList = (IList<ToDo>)sQLToDoRepository.GetInbox();
            }
            if (_context.Project != null)
            {
                ProjectsList = (IList<Project>)sQLToDoRepository.GetAllProjects();
            }

            if (_context.Category != null)
            {
                CategoriesList = (IList<Category>)sQLToDoRepository.GetAllCategories();
            }

            if ((id != null) && (InboxList.Select(p => p.Id).ToList().Contains((int)id)))
            {
                showDetails = true;
                DetailsId = (int)id;
            }

            if (nav != null)
            {
                if ((int)nav == 1)
                {
                    wantProjects = true;
                    wantCategories = false;
                }
                else
                {
                    wantProjects = false;
                    wantCategories = true;
                }
            }

        }
        public IActionResult OnPostUpdate()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.UpdateTask(Int32.Parse(Request.Form["id"]), Request.Form["upd"]);
            }
            return RedirectToPage("/Inbox");
        }

        public IActionResult OnPostUpdateDetails()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.UpdateTask(Int32.Parse(Request.Form["id"]), Request.Form["upd"]);
            }
            return RedirectToPage("/Inbox", new { id = Request.Form["id"] });
        }

        public IActionResult OnPostAdd()
        {
            if (Request.Form["taskname"] != "")
            {
                var newToDo = new ToDo
                {
                    TaskName = Request.Form["taskname"],
                    IsUrgent = false
                };
                sQLToDoRepository.AddNewTask(newToDo);
            }
            return RedirectToPage("/Inbox");
        }
        public IActionResult OnPostAddProject()
        {
            if (Request.Form["pname"] != "")
            {
                var newProject = new Project
                {
                    ProjectName = Request.Form["pname"],
                    ProjectColour = "#e2e2e2;"

                };
                sQLToDoRepository.AddNewProject(newProject);
            }
            return RedirectToPage("/Inbox", new { nav = 1 });
        }

        public IActionResult OnPostAddCategory()
        {
            if (Request.Form["cname"] != "")
            {
                var newCategory = new Category
                {
                    CategoryName = Request.Form["cname"],
                    CategoryColour = "#e2e2e2;"
                };
                sQLToDoRepository.AddNewCategory(newCategory);
            }
            return RedirectToPage("/Inbox", new { nav = 2 });
        }

        public IActionResult OnPostChangeTaskName()
        {
            if (Request.Form["nwetname"] != "")
            {
                sQLToDoRepository.UpdateTaskName(Int32.Parse(Request.Form["id"]), Request.Form["nwetname"]);
            }
            return RedirectToPage("/Inbox", new { id = Request.Form["id"] });
        }

        public IActionResult OnPostDeleteTask()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.DeleteTask(Int32.Parse(Request.Form["id"]));
            }
            return RedirectToPage("/Inbox");
        }
    }
}

ToDoList/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDoList.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ToDoList/Pages/Project.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDoList.Data;
using ToDoList.Models;

namespace ToDoList.Pages
{
    public class ProjectModel : PageModel
    {
        private readonly ToDoList.Data.ToDoListContext _context;
        private SQLToDoRepository sQLToDoRepository;

        public IList<ToDo> ProjectTaskList { get; set; } = default!;
        public IList<Project> ProjectsList { get; set; } = default!;
        public IList<Category> CategoriesList { get; set; } = default!;

        public bool wantProjects = true;
        public bool wantCategories = false;
        public bool showDetails = false;
        public bool showProjectInfo = false;
        public int DetailsId = 0;
        public int projectId = 0;

        public ProjectModel(ToDoList.Data.ToDoListContext context)
        {
            _context = context;
            sQLToDoRepository = new SQLToDoRepository(_context);
        }

        public void OnGet(int pId, int? nav, int? id, bool? info)
        {
            if (_context.ToDo != null)
            {
                ProjectTaskList = (IList<ToDo>)sQLToDoRepository.GetOneProject(pId);
            }
            if (_context.Project != null)
            {
                ProjectsList = (IList<Project>)sQLToDoRepository.GetAllProjects();
            }

            if (_context.Category != null)
            {
                CategoriesList = (IList<Category>)sQLToDoRepository.GetAllCategories();
            }

            projectId = pId;

            if ((info != null) && (bool)info)
            {
                showProjectInfo = true;
                //showDetails = false;
            }
            else if ((id != null) && (ProjectTaskList.Select(p => p.Id).ToList().Contains((int)id)))
            {
                showDetails = true;
                DetailsId = (int)id;
                //showProjectInfo = false;
            }

            if (nav != null)
            {
                if ((int)nav == 1)
                {
                    wantProjects = true;
                    wantCategories = false;
                }
                else
                {
                    wantProjects = false;
                    wantCategories = true;
                }
            }
        }

        public IActionResult OnPostUpdate()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.UpdateTask(Int32.Parse(Request.Form["id"]), Request.Form["upd"]);
            }
            return RedirectToPage("/Project", new { pid = Request.Form["pid"] });
        }

        public IActionResult OnPostUpdateDetails()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.UpdateTask(Int32.Parse(Request.Form["id"]), Request.Form["upd"]);
            }
            return RedirectToPage("/Project", new { id = Request.Form["id"], pid = Request.Form["pid"] });
        }

        public IActionResult OnPostAdd()
        {
            if (Request.Form["taskname"] != "")
            {
                var newToDo = new ToDo
                {
                    TaskName = Request.Form["taskname"],
                    Project = sQLToDoRepository.GetProjectInfo(Int32.Parse(Request.Form["pid"])),
                    IsUrgent = false
                };
                sQLToDoRepository.AddNewTask(newToDo);
            }
            return RedirectToPage("/Project", new { pid = Request.Form["pid"] });
        }

        public IActionResult OnPostAddProject()
        {
            if (Request.Form["pname"] != "")
            {
                var newProject = new Project
                {
                    ProjectName = Request.Form["pname"],
                    ProjectColour = "#e2e2e2;"

                };
                sQLToDoRepository.AddNewProject(newProject);
            }
            return RedirectToPage("/Project", new { pid = Request.Form["pid"], nav = 1 });
        }

        public IActionResult OnPostAddCategory()
        {
            if (Request.Form["cname"] != "")
            {
                var newCategory = new Category
                {
                    CategoryName = Request.Form["cname"],
                    CategoryColour = "#e2e2e2;"
                };
                sQLToDoRepository.AddNewCategory(newCategory);
            }
            return RedirectToPage("/Project", new { pid = Request.Form["pid"], nav = 2 });
        }

        public IActionResult OnPostChangeTaskName()
        {
            if (Request.Form["newtname"] != "")
            {
                sQLToDoRepository.UpdateTaskName(Int32.Parse(Request.Form["id"]), Request.Form["newtname"]);
            }
            return RedirectToPage("/Project", new { id = Request.Form["id"], pid = Request.Form["pid"] });
        }

        public IActionResult OnPostDeleteTask()
        {
            if (Request.Form["id"] != "")
            {
                sQLToDoRepository.DeleteTask(Int32.Parse(Request.Form["id"]));
            }
            return RedirectToPage("/Project", new { pid = Request.Form["pid"] });
        }

        public IActionResult OnPostDeleteProject()
        {
            if (Request.Form["pid"] != "")
            {
                sQLToDoRepository.DeleteProject(Int32.Parse(Request.Form["pid"]));
            }
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostChangeProjectName()
        {
            if (Request.Form["newpname"] != "")
            {
                sQLToDoRepository.UpdateProjectName(Int32.Parse(Request.Form["pid"]), Request.Form["newpname"]);
            }
            return RedirectToPage("/Project", new { pid = Request.Form["pid"], info = true });
        }
    }
}

ToDoList/Pages/Category.cshtml
@page
@model ToDoList.Pages.CategoryModel
@{
}

<header>
    <div class="navbar">
          <div class="leftnavbar @((Model.wantProjects || Model.wantCategories)? "minnav" : "")">
              <a asp-page="/Index">Priority</a>
              <a asp-page="/Inbox">Inbox</a>
              <a asp-page="/Category" asp-route-nav="1" asp-route-cid="@Model.categoryId">Projects</a>
              <a asp-page="/Category" class="chosen" asp-route-nav="2" asp-route-cid="@Model.categoryId">Categories</a>
          </div>
          <div class="rightnavbar">
            @if (Model.wantProjects)
            {
                <div class="columnname nav">
                    <span>Projects</span>
                </div>
                @foreach (var item in Model.ProjectsList)
                {
                    <a asp-page="/Project" asp-route-pid="@item.Id">@item.ProjectName</a>
                }
                <div class="add">
                    <div class="textline">
                        <form method="post">
                            <input type="hidden" name="cid" value="@Model.categoryId"/>
                            <button asp-page-handler="AddProject" class="i">&#9547;</button>
                            <input type="text" class="inputtext" name="pname" placeholder="New Project" >
                        </form>
                    </div>
                </div>
            }
            @if (Model.wantCategories)
            {
              <div class="columnname nav">
                  <span>Categories</span>
              </div>
              @foreach (var item in Model.CategoriesList)
                {
                    <a asp-page="/Category" asp-route-cid="@item.Id" class="@(item.Id == Model.categoryId ? "chosen" : "")" >@item.CategoryName</a>
                }
                <div class="add">
                    <div class="textline">
                        <form method="post">
                            <input type="hidden" name="cid" value="@Model.categoryId"/>
                            <button asp-page-handler="AddCategory" class="i">&#9547;</button>
                            <input type="text" class="inputtext" name="cname" placeholder="New Category" >
                        </form>
                    </div>
                </div>
            }
          </div>
    </div>
</header>


<div class="bigwindow">
<div class="mainlist">
        <div class="columnname">
              <span>@Model.CategoriesList.First(c => c.Id == Model.categoryId).CategoryName</span>
              <a class="info" asp-page="/Category" asp-route-info="true" asp-route-cid="@Model.categoryId">&#8505;</a>
        </div>
        <div class="listlines @((Model.showDetails || Model.showCategoryInfo ) ? "" : "fullview")">
            <div class="add">
                <div class="textline">
                    <form method="post">
                        <input type="hidden" name="cid" value="@Model.categoryId"/>
                        <button asp-page-handler="Add" class="i">&#9547;</button>
                        <input type="text" class="inputtext" name="taskname" placeholder="Enter task name" >
                    </form>
                </div>
            </div>
            @foreach (var item in Model.CategoryTaskList) {
                <div class="row @(item.IsDone ? "completed" : "")">
                    <form method="post">
                        <input type="hidden" name="upd" value="d"/>
                        <input type="hidden" name="id" value="@item.Id"/>
                        <input type="hidden" name="cid" value="@Model.categoryId"/>
                    <button asp-page-handler="Update" class="done">
                                <span class="circle @(item.IsDone ? "checkmark" : "")">
                                @if(item.IsDone){
                                <p>&#10003;</p>
                                }
                                </span>
                        </button>
                    </form>
                    <a asp-page="/Category" asp-route-id="@item.Id" asp-route-cid="@Model.categoryId">@item.TaskName</a>
                    <form method="post">
                        <input type="hidden" name="upd" value="s"/>
                        <input type="hidden" name="id" value="@item.Id"/>
                        <input type="hidden" name="cid" value="@Model.categoryId"/>
                    <button  asp-page-handler="Update" class="starbutton">
                                <span class="circle star @(item.IsUrgent ? "urgent" : "")"></span>
                            </button>
                    </form>
                </div>
            }
        </div>
        @if(Model.showDetails)
        {
            <div class="details">

                <div class="row @(Model.CategoryTaskList.First(t => t.Id == Model.DetailsId).IsDone ? "completed" : "")">
                    <form method="post">
                        <input type="hidden" name="upd" value="d"/>
                        <input type="hidden" name="id" value="@Model.DetailsId"/>
                        <input type="hidden" name="cid" value="@Model.categoryId"/>
                        <button asp-page-handler="UpdateDetails"  class="done">
                                <span class="circle @(Model.CategoryTaskList.First(t => t.Id == Model.DetailsId).IsDone ? "checkmark" : "")">
                                @if(Model.CategoryTaskList.First(t => t.Id == Model.DetailsId).IsDone){
                                <p>&#10003;</p>
                                }
                                </span>
                        </button>
                    </form>
                    <a>@(Model.CategoryTaskList.First(t => t.Id == Model.DetailsId).TaskName)</a>
                    <form method="post">
                        <input type="hidden" name="upd" value="s"/>
                        <input type="hidden" name="id" value="@Model.DetailsId"/>
                        <input type="hidden" name="cid" value="@Model.categoryId"/>
                        <button  asp-page-handler="UpdateDetails" class="starbutton">
                                <span class="circle star @(Model.CategoryTaskList.First(t => t.Id == Model.DetailsId).IsUrgent ? "urgent" : "")"></span>
                        </button>
                    </form>
                </div>

                <div class="row">
                    <div class="textline">
                        <form method="post">
                            <input type="hidden" name="id" value="@Model.DetailsId"/>
                            <input type="text" class="inputtext" name="newtname" value="@(Model.CategoryTaskList.First(t => t.Id == Model.DetailsId).TaskName)" >
                            <input type="hidden" name="cid" value="@Model.categoryId"/>
                            <button asp-page-handler="ChangeTaskName" class="savebutton">Save</button>
                        </form>
                    </div>
                </div>
                @*<div class="ditattributes">

                </div>*@

                <div class="columnname bottom">
                    <a class="l" asp-page="/Category" asp-route-id="" asp-route-cid="@Model.categoryId">&#8677;</a>
                    <a asp-page="/Category" asp-route-id="@(Model.CategoryTaskList.TakeWhile(t => t.Id != Model.DetailsId).DefaultIfEmpty(Model.CategoryTaskList[Model.CategoryTaskList.Count - 1]).LastOrDefault().Id)" asp-route-cid="@Model.categoryId">&#8896;</a>
                    <a asp-page="/Category" asp-route-id="@(Model.CategoryTaskList.SkipWhile(t => t.Id != Model.DetailsId).Skip(1).DefaultIfEmpty(Model.CategoryTaskList[0]).FirstOrDefault().Id)" asp-route-cid="@Model.categoryId">&#8897;</a>
                    
                    <form method="post">
                            <input type="hidden" name="id" value="@Model.DetailsId"/>
                            <input type="hidden" name="cid" value="@Model.categoryId"/>
                            <button asp-page-handler="DeleteTask" class="trash">&#128465;</button>
                    </form>
                </div>


            </div>
        }


        @if(Model.showCategoryInfo)
        {
            <div class="details">
                <div class="columnname">
                </div>
                <div class="row">
                    <div class="textline">
                        <form method="post">
                            <input type="text" class="inputtext" name="newcname" value="@(Model.CategoriesList.First(c => c.Id == Model.categoryId).CategoryName)" >
                            <input type="hidden" name="cid" value="@Model.categoryId"/>
                            <button asp-page-handler="ChangeCategoryName" class="savebutton">Save</button>
                        </form>
                    </div>
                </div>

                <div class="columnname bottom">
                    <a class="l" asp-page="/Category" asp-route-info="false" asp-route-pic="@Model.categoryId">&#8677;</a>
                    
                    <form method="post">
                            <input type="hidden" name="cid" value="@Model.categoryId"/>
                            <button asp-page-handler="DeleteCategory" class="trash">&#128465;</button>
                    </form>
                </div>
            </div>
        }


        <div class="columnname bottom">
              <span>@Model.CategoryTaskList.Where(t => t.IsDone == false).Count() left</span>
        </div>

</div>

</div>